version: "3.8"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./ssl:/root/ssl:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
